### ISSUE TITLE
team lock-in UI + backend integration

### ISSUE THREAD

**Issue by asipser** [weblab-staff/submission-portal#11]
We need a mechanism that allows students to lock in their team. We do not have UI in place to do this right now which needs to be designed sooner rather than later.

After students lock in their team they will get a github generated for them! 

We also want some setting from an admin page as well that allows us to specify a team-lockin deadline. We also need to bake this notion of team lockin date into backend class settings, so we can auto-generate githubs for the rest.

**Comment by jynnie** [comment]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/7284723/62015413-38d57200-b160-11e9-8d11-92c52c9c3524.png">
